#!/bin/bash -ex
source $(dirname $0)/lib/oo
source $(dirname $0)/lib/unixbox

# If you want to trap EXIT, and want method_missing to work,
# then your own trap should start with the method_missing call.
# e.g. trap 'method_missing; echo "Goodbye.";' EXIT

new jumpbox is unixbox 192.168.0.14
jumpbox.ssh ls

# unixbox.mkdir doesn't exist.
# This is implemented through unixbox.method_missing
jumpbox.mkdir -p /tmp/woot
