#!/bin/bash
# vim: tabstop=4 shiftwidth=4 softtabstop=4

#    Copyright 2011 Cloudscaling Group, Inc
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

source $(dirname $0)/lib/oo

function unixbox::new {
    self=$1; shift
    instance_var $self ip $1;
    instance_var $self username $USER;
};

function unixbox::ssh {
    self=$1; shift
    ssh $($self.username)@$($self.ip) "$@";
};

function unixbox::method_missing {
    self=$1; shift
    $self.ssh "$@"
}

# Basic object creation (box) from class (unixbox)
new box unixbox 192.168.0.14

# kwargs are handled like this...
# Also, we support an optional 'is' string between object and classnames.
USER=nobody new box is unixbox 192.168.0.14

# There is an ssh method in unixbox.
box.ssh ls

# unixbox.mkdir doesn't exist.
# This is implemented through unixbox.method_missing
box.mkdir -p /tmp/woot
